version: "3.9"
services:
  stacks-api:
    image: hirosystems/stacks-blockchain-api:7.1.1
    depends_on:
      - postgres
    ports:
      - 3999:3999
    expose:
      - "3700"
    environment:
      NODE_ENVIRONMENT: production
      STACKS_API_LOG_LEVEL: debug
      STACKS_CHAIN_ID: "0x00000001"
      STACKS_BLOCKCHAIN_API_HOST: "0.0.0.0"
      STACKS_BLOCKCHAIN_API_PORT: 3999
      STACKS_CORE_EVENT_HOST: "0.0.0.0"
      STACKS_CORE_EVENT_PORT: 3700
      PG_HOST: postgres
      PG_PORT: 5490
      PG_USER: postgres
      PG_PASSWORD: postgres
      PG_DATABASE: stacks_blockchain_api
      PG_SCHEMA: public
      STACKS_CORE_RPC_HOST: stacks-node
      STACKS_CORE_RPC_PORT: 20443

  postgres:
    image: "postgres:14"
    expose:
      - "5490"
    volumes:
      - ./data/pg:/pg-data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stacks_blockchain_api
      PGPORT: 5490
      PGDATA: /pg-data

  stacks-node:
    build:
      dockerfile: ./dockerfiles/stacks-node.Dockerfile
    depends_on:
      - stacks-api
      - bitcoin
    ports:
      - 20443:20443 #rpc
      - 20444:20444 #p2p
    environment:
      STACKS_EVENT_OBSERVER: stacks-api:3700
    volumes:
      - ./config/stacks-node.toml:/config.toml
      - ./data/stacks-node:/chainstate
    command: stacks-node start --config=/config.toml
    healthcheck:
      test: curl -f http://127.0.0.1:20443/v2/pox || exit 1

  bitcoin:
    image: ruimarinho/bitcoin-core:22
    volumes:
      - ./data/bitcoin:/home/bitcoin/.bitcoin
      - ./bitcoin.conf:/home/bitcoin/.bitcoin/bitcoin.conf
    ports:
      - 8333:8333 #p2p
      - 8332:8332 #rpc
    healthcheck:
      test: curl -f --data-binary '{"jsonrpc":"1.0","id":"curltext","method":"getblockchaininfo","params":[]}' -H 'content-type:text/plain;' http://btc:btc@127.0.0.1:8332 || exit 1

  ord:
    build:
      dockerfile: ./dockerfiles/ord.Dockerfile
    depends_on:
      - bitcoin
    restart: unless-stopped
    volumes:
      - ./config/bitcoin-rpc-cookie:/cookie
      - ./data/ord:/data
    environment:
      RUST_LOG: info
    # --index-sats (disabled for now, it's slow and massive)
    command: ord --rpc-url bitcoin:8332 --cookie-file /cookie --data-dir /data server
    ports:
      - 7982:80

  tms-pg:
    image: "postgres:14"
    expose:
      - '5590'
    volumes:
      - ./data/tms-pg:/pg-data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tms
      PGPORT: 5590
      PGDATA: /pg-data

  tms:
    image: hirosystems/token-metadata-service:0.1.0
    depends_on:
      tms-pg:
        condition: service_started
      stacks-node:
        condition: service_healthy
    environment:
      RUN_MODE: default
      API_HOST: 0.0.0.0
      API_PORT: 3000
      PGHOST: tms-pg
      PGPORT: 5590
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: tms
      BLOCKCHAIN_API_PGHOST: postgres
      BLOCKCHAIN_API_PGPORT: 5490
      BLOCKCHAIN_API_PGUSER: postgres
      BLOCKCHAIN_API_PGPASSWORD: postgres
      BLOCKCHAIN_API_PGDATABASE: stacks_blockchain_api
      STACKS_NODE_RPC_HOST: stacks-node
      STACKS_NODE_RPC_PORT: 20443
      PUBLIC_GATEWAY_IPFS: https://cloudflare-ipfs.com
      PUBLIC_GATEWAY_ARWEAVE: https://arweave.net
      METADATA_MAX_IMMEDIATE_URI_RETRIES: 1
      METADATA_FETCH_TIMEOUT_MS: 5000
      JOB_QUEUE_CONCURRENCY_LIMIT: 20
      PG_CONNECTION_POOL_MAX: 20
    ports:
      - 3000:3000
